// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf2l1KoUWMwVhDxAKbu7HZoAE5XP6O4Gk',
    appId: '1:295571864630:web:81a84bd6bab308ba226c97',
    messagingSenderId: '295571864630',
    projectId: 'student1-55b0b',
    authDomain: 'student1-55b0b.firebaseapp.com',
    storageBucket: 'student1-55b0b.firebasestorage.app',
    measurementId: 'G-BJ2H1Q4L32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCD2eV_Gbez9Eu8er8QxpS0zlk4dNRYvw',
    appId: '1:295571864630:android:aba709cf6a9db9f6226c97',
    messagingSenderId: '295571864630',
    projectId: 'student1-55b0b',
    storageBucket: 'student1-55b0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_GPBDz3fE4SiR6BldVogKe8gLn_jQYUA',
    appId: '1:295571864630:ios:8fcaa4e4f0a2d5bc226c97',
    messagingSenderId: '295571864630',
    projectId: 'student1-55b0b',
    storageBucket: 'student1-55b0b.firebasestorage.app',
    androidClientId:
        '295571864630-iss24pkqa1v99ghvvolc43gqpp6ii01h.apps.googleusercontent.com',
    iosClientId:
        '295571864630-cit60h0es7f0mugsuuq0ilt9ei1q8gpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.taalaam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_GPBDz3fE4SiR6BldVogKe8gLn_jQYUA',
    appId: '1:295571864630:ios:8fcaa4e4f0a2d5bc226c97',
    messagingSenderId: '295571864630',
    projectId: 'student1-55b0b',
    storageBucket: 'student1-55b0b.firebasestorage.app',
    androidClientId:
        '295571864630-iss24pkqa1v99ghvvolc43gqpp6ii01h.apps.googleusercontent.com',
    iosClientId:
        '295571864630-cit60h0es7f0mugsuuq0ilt9ei1q8gpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.taalaam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf2l1KoUWMwVhDxAKbu7HZoAE5XP6O4Gk',
    appId: '1:295571864630:web:4c5fc22cec6402e0226c97',
    messagingSenderId: '295571864630',
    projectId: 'student1-55b0b',
    authDomain: 'student1-55b0b.firebaseapp.com',
    storageBucket: 'student1-55b0b.firebasestorage.app',
    measurementId: 'G-9TTVT4Z94C',
  );
}
